### ISSUE TITLE
Instructions on how to run grunt tasks would be helpful

### ISSUE THREAD

**Issue by kaiyoma** [themegrill/spacious#15]
I forked the repo and tried to run the grunt tasks, but I'm getting errors. Some instructions on how to properly configure my dev environment would be helpful.

```
$ grunt zip
Running "jshint:all" (jshint) task
>> 4 files lint free.

Running "makepot:dist" (makepot) task
Warning: Error: not found: php Use --force to continue.

Aborted due to warnings.
```

**Comment by shivapoudel** [comment]
@kaiyoma You should add php command into your environment variable and it should be accessible.

**Comment by kaiyoma** [comment]
Yup, that fixed it. Thanks!

**Comment by shivapoudel** [comment]
Good to hear @kaiyoma 👍
